'use strict';
const $=id=>document.getElementById(id), fields=['name','currency','portions','packaging','labor','delivery','overhead','fee','margin','sale'];
let lang='fa',books=[];
const EN={title:'Price your next order with clarity.',subtitle:'Calculate your own ingredient and order costs. Your recipes stay on your device.',notice:'An estimate, not guaranteed profit. Tax, depreciation and omitted expenses are excluded. Sample figures are fictional, not market prices.',new:'Load teaching example',save:'Save in this browser',saved:'Saved recipes',backup:'JSON backup',restore:'Restore JSON',csv:'Export CSV',order:'1. Order details',name:'Order name',currency:'Currency label — changing it does not convert values',portions:'Portions in this order',ingredients:'2. Ingredients for the entire order',yieldHelp:'Used quantity means usable amount after loss. Yield is the usable percentage of purchased quantity. Purchase and usage units must share a dimension.',add:'+ Add ingredient',costs:'3. Costs and target price',packaging:'Packaging per portion',labor:'Labour for entire order',delivery:'Delivery for entire order',overhead:'Other allocated costs',fee:'Sales commission on total revenue (%)',margin:'Target margin after included costs (%)',sale:'Your total selling price (0 = calculated price)',calculate:'Calculate order',results:'Cost and price summary',details:'Ingredient cost breakdown',formula:'Target price = total cost ÷ (1 − commission rate − target margin). Margin is a share of sales, not a markup on cost.',print:'Print cost summary / Save PDF',privacy:'Data stays on your device. Clearing browser data can delete saved recipes; export a JSON backup. There is no automatic bank, supplier or internet connection.',guide:'Instructions and limitations'};
const FA=Object.fromEntries([...document.querySelectorAll('[data-i]')].map(e=>[e.dataset.i,e.textContent]));
const texts={fa:{ingredient:'نام ماده',buyQty:'مقدار بسته خرید',buyUnit:'واحد خرید',price:'قیمت همان بسته',useQty:'مصرف قابل استفاده در کل سفارش',useUnit:'واحد مصرف',yield:'بازده قابل استفاده (%)',remove:'حذف',cost:'کل هزینه‌های واردشده',perPortion:'هزینه هر پرس',suggested:'قیمت هدف کل سفارش',suggestedPortion:'قیمت هدف هر پرس',contribution:'مانده پس از هزینه‌ها و کارمزد',margin:'حاشیه برآوردی (%)',stressContribution:'مانده با ۱۰٪ افزایش هزینه مواد',sale:'مبلغ فروش کل',commission:'کارمزد فروش',invalid:'ورودی معتبر نیست. مقدار خرید و تعداد پرس باید مثبت، بازده بیشتر از صفر و حداکثر ۱۰۰ و مجموع کارمزد و حاشیه کمتر از ۱۰۰ باشد. واحدها را بررسی کنید.',stored:'ذخیره شد. برای نگهداری مطمئن پشتیبان JSON بگیرید.',storage:'ذخیره مرورگر ممکن نیست؛ از پشتیبان JSON استفاده کنید.',restored:'پشتیبان معتبر بازیابی شد.',ready:'محاسبه انجام شد؛ این مانده، سود خالص حسابداری نیست.'},en:{ingredient:'Ingredient',buyQty:'Purchase pack quantity',buyUnit:'Purchase unit',price:'Price of that pack',useQty:'Usable quantity for whole order',useUnit:'Usage unit',yield:'Usable yield (%)',remove:'Remove',cost:'Total included cost',perPortion:'Cost per portion',suggested:'Target order price',suggestedPortion:'Target price per portion',contribution:'Balance after costs and commission',margin:'Estimated margin (%)',stressContribution:'Balance if ingredient costs rise 10%',sale:'Total selling price',commission:'Sales commission',invalid:'Check inputs. Purchase quantity and portions must be positive, yield above zero and at most 100, fee plus target margin below 100, and units compatible.',stored:'Saved. Export JSON for a durable backup.',storage:'Browser storage is unavailable. Export a JSON backup.',restored:'Valid backup restored.',ready:'Calculated. The balance is not accounting net profit.'}};
const example={name:'نمونه آموزشی / Teaching example',currency:'IRT',portions:10,packaging:10000,labor:200000,delivery:50000,overhead:50000,fee:5,margin:20,sale:0,ingredients:[{name:'ماده نمونه A / Example A',buyQty:1,buyUnit:'kg',price:200000,useQty:2,useUnit:'kg',yield:80},{name:'ماده نمونه B / Example B',buyQty:1,buyUnit:'kg',price:100000,useQty:1,useUnit:'kg',yield:100}]};
function row(item){const box=document.createElement('div');box.className='ingredient';const specs=[['name','ingredient','text'],['buyQty','buyQty','number'],['buyUnit','buyUnit','select'],['price','price','number'],['useQty','useQty','number'],['useUnit','useUnit','select'],['yield','yield','number']];for(const [key,label,type]of specs){const l=document.createElement('label'),s=document.createElement('span');s.textContent=texts[lang][label];l.append(s);const i=document.createElement(type==='select'?'select':'input');i.dataset.key=key;if(type==='select'){for(const u of ['g','kg','ml','l','each']){const o=document.createElement('option');o.value=u;o.textContent=u;i.append(o);}}else{i.type=type;if(type==='number'){i.min=['buyQty','yield'].includes(key)?'.000001':'0';i.step='any';i.max=key==='yield'?'100':'1000000000000';}else i.maxLength=100;i.required=true;}i.value=item[key]??'';l.append(i);box.append(l);}const b=document.createElement('button');b.type='button';b.textContent=texts[lang].remove;b.onclick=()=>{box.remove();$('results').hidden=true;};box.append(b);$('ingredients').append(box);}
function read(){const r={};for(const k of fields)r[k]=['name','currency'].includes(k)?$(k).value:Number($(k).value);r.ingredients=[...document.querySelectorAll('.ingredient')].map(b=>Object.fromEntries([...b.querySelectorAll('[data-key]')].map(i=>[i.dataset.key,['name','buyUnit','useUnit'].includes(i.dataset.key)?i.value:Number(i.value)])));return r;}
function fill(r){for(const k of fields)$(k).value=r[k];$('ingredients').replaceChildren();r.ingredients.forEach(row);$('results').hidden=true;}
function money(n){return new Intl.NumberFormat(lang==='fa'?'fa-IR':'en-US',{maximumFractionDigits:2}).format(n);}
function calculate(){try{const r=CostKit.validate(read()),v=CostKit.calculate(r);$('metrics').replaceChildren();for(const k of ['cost','perPortion','suggested','suggestedPortion','sale','commission','contribution','margin','stressContribution']){const d=document.createElement('div');d.className='metric';const label=document.createElement('span'),b=document.createElement('b'),unit=document.createElement('small');label.textContent=texts[lang][k];b.textContent=money(v[k]);unit.textContent=k==='margin'?'%':r.currency;d.append(label,b,unit);$('metrics').append(d);}$('lines').replaceChildren();for(const l of v.lines){const li=document.createElement('li');li.textContent=l.name+': '+money(l.cost)+' '+r.currency;$('lines').append(li);}$('results').hidden=false;$('status').textContent=texts[lang].ready;return {r,v};}catch(e){$('results').hidden=true;$('status').textContent=texts[lang].invalid;return null;}}
function download(name,type,text){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function savedList(){const s=$('saved');while(s.options.length>1)s.remove(1);books.forEach((b,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=b.name;s.append(o);});}
$('recipe').addEventListener('submit',e=>{e.preventDefault();calculate();});$('recipe').addEventListener('input',()=>{$('results').hidden=true;});
$('add').onclick=()=>{if(document.querySelectorAll('.ingredient').length>=50)return;row({name:'',buyQty:1,buyUnit:'kg',price:0,useQty:1,useUnit:'kg',yield:100});};
$('new').onclick=()=>{fill(example);calculate();};$('saved').onchange=()=>{if($('saved').value!=='')fill(books[Number($('saved').value)]);};
$('save').onclick=()=>{const result=calculate();if(!result)return;if(books.length>=100){$('status').textContent='100 recipe limit';return;}books.push(result.r);savedList();try{localStorage.setItem('zm-costkit-v1',JSON.stringify(books));$('status').textContent=texts[lang].stored;}catch{$('status').textContent=texts[lang].storage;}};
$('backup').onclick=()=>{const result=calculate();if(result)download('zomorod-costkit-backup.json','application/json',JSON.stringify({version:1,recipes:[...books,result.r]},null,2));};
$('restore').onchange=async()=>{try{const f=$('restore').files[0];if(!f||f.size>500000)throw Error();const d=JSON.parse(await f.text());if(d.version!==1||!Array.isArray(d.recipes)||d.recipes.length>101||!d.recipes.length)throw Error();const restored=d.recipes.map(CostKit.validate);books=restored.slice(0,100);fill(restored[restored.length-1]);savedList();$('status').textContent=texts[lang].restored;}catch{$('status').textContent=texts[lang].invalid;}$('restore').value='';};
$('csv').onclick=()=>{const z=calculate();if(!z)return;const lines=[['metric','value','currency'],...Object.entries(z.v).filter(([k,v])=>typeof v==='number').map(([k,v])=>[k,v,z.r.currency]),['recipe',z.r.name,z.r.currency]];download('zomorod-costkit.csv','text/csv;charset=utf-8','\ufeff'+lines.map(r=>r.map(CostKit.csvCell).join(',')).join('\r\n'));};
$('print').onclick=()=>{if(calculate())window.print();};
$('language').onclick=()=>{const r=read();lang=lang==='fa'?'en':'fa';document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'?'rtl':'ltr';document.querySelectorAll('[data-i]').forEach(e=>{e.textContent=(lang==='fa'?FA:EN)[e.dataset.i]||e.textContent;});$('language').textContent=lang==='fa'?'English':'فارسی';fill(r);savedList();calculate();};
try{const saved=JSON.parse(localStorage.getItem('zm-costkit-v1')||'[]');if(Array.isArray(saved)&&saved.length<=101)books=saved.map(CostKit.validate);}catch{}savedList();fill(example);calculate();
