import json

from django.core.management.base import BaseCommand, CommandError
from core.autonomous_brain import AutonomousBrain
from core.factory_agent_runtime import FactoryAgentRuntime
from core.factory_tool_pack import build_factory_gateway
from core.models import AgentTask
from core.worker_runner import WorkerRunner


class Command(BaseCommand):
    help = "Execute or resume one queued Product Factory task through its bounded agent runtime."

    def add_arguments(self, parser):
        parser.add_argument("--task-id", type=int)
        parser.add_argument("--product-id", type=int)
        parser.add_argument("--payload-json", default="")
        parser.add_argument("--result-json", default="", help="Deprecated: specialist outputs are never accepted as task inputs.")

    def handle(self, *args, **opts):
        if opts.get("result_json"):
            raise CommandError("--result-json is disabled; Factory outputs are generated by the registered execution adapter.")
        qs = AgentTask.objects.filter(action_type__startswith="product_", status="queued")
        task = qs.filter(pk=opts["task_id"]).first() if opts.get("task_id") else qs.order_by("created_at").first()
        if opts.get("task_id") and not task:
            raise CommandError("The requested task is not a queued Product Factory task.")
        if not task and opts.get("payload_json"):
            try:
                request = json.loads(opts["payload_json"])
            except json.JSONDecodeError as exc:
                raise CommandError("--payload-json must be valid JSON.") from exc
            if not isinstance(request, dict) or not request.get("goal"):
                raise CommandError("--payload-json must contain a goal.")
            try:
                task = AutonomousBrain().plan_product_factory_step(
                    payload={"goal": request["goal"], "constraints": request.get("constraints", [])},
                    product_id=opts.get("product_id"),
                )
            except RuntimeError as exc:
                raise CommandError(str(exc)) from exc
        if not task:
            self.stdout.write("FACTORY_IDLE")
            return
        try:
            done = WorkerRunner(
                build_factory_gateway(), factory_executor=FactoryAgentRuntime()
            ).run(task.pk)
        except Exception as exc:
            task.refresh_from_db()
            self.stdout.write(f"FACTORY_WAIT task={task.pk} status={task.status} reason={str(exc)[:500]}")
            return
        self.stdout.write(self.style.SUCCESS(
            f"FACTORY_DONE task={done.pk} action={done.action_type} verified=True"
        ))
