# Generated by Django 5.2 on 2026-09-25 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_seed_core_research_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgearticle",
            name="source_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="knowledge_articles",
                to="core.report",
            ),
        ),
    ]
