# Generated by Django 5.2.17 on 2026-09-25 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(max_length=10)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("status", models.CharField(default="awaiting_approval", max_length=30)),
                ("provider", models.CharField(default="not_configured", max_length=50)),
                ("provider_reference", models.CharField(blank=True, default="", max_length=200)),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="payment_intent", to="core.order")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entry_type", models.CharField(max_length=30)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(max_length=10)),
                ("reference", models.CharField(max_length=200, unique=True)),
                ("metadata", models.JSONField(default=dict)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="core.order")),
                ("payment_intent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="core.paymentintent")),
            ],
            options={"abstract": False},
        ),
    ]
