# Generated by Django 5.2.17 on 2026-09-25 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_paymentintent_ledgerentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=50)),
                ("event_id", models.CharField(max_length=200)),
                ("event_type", models.CharField(max_length=50)),
                ("payload_hash", models.CharField(max_length=128)),
                ("status", models.CharField(default="received", max_length=30)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("payment_intent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="webhook_events", to="core.paymentintent")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("provider", "event_id"), name="unique_payment_webhook_event")
                ]
            },
        ),
    ]
