# Generated by Django 5.2.17 on 2026-09-25 12:39

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_paymentwebhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2019, 11, 16))),
                ('company_news_daily', models.PositiveIntegerField(default=4)),
                ('world_news_daily', models.PositiveIntegerField(default=4)),
                ('reports_daily', models.PositiveIntegerField(default=4)),
                ('publication_requires_approval', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter Schedule',
                'verbose_name_plural': 'Newsletter Schedules',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('kind', models.CharField(choices=[('company', 'Company'), ('world', 'World'), ('research', 'Research')], default='world', max_length=20)),
                ('retrieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-retrieved_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsletterStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_type', models.CharField(choices=[('company', 'Company Activity'), ('world', 'World News'), ('report', 'Company Report')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('author_name', models.CharField(default='مجتبی روزگار', max_length=200)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(max_length=128, unique=True)),
                ('source_fingerprint', models.CharField(blank=True, db_index=True, max_length=128)),
                ('seo_keywords', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newsletter_stories', to='core.agent')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='core.newslettersource')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='NewsletterPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('site', 'Website'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('x', 'X'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('eitaa', 'Eitaa'), ('rubika', 'Rubika'), ('bale', 'Bale')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('published', 'Published'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='queued', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.newsletterstory')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsletterAgentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('responsibility', models.TextField()),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_parent', to='core.agent')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_children', to='core.agent')),
            ],
            options={
                'ordering': ('sequence',),
                'constraints': [models.UniqueConstraint(fields=('parent', 'sequence'), name='unique_newsletter_agent_sequence')],
            },
        ),
        migrations.AddIndex(
            model_name='newsletterstory',
            index=models.Index(fields=['story_type', 'status', 'published_at'], name='core_newsle_story_t_93a80d_idx'),
        ),
        migrations.AddConstraint(
            model_name='newsletterpublication',
            constraint=models.UniqueConstraint(fields=('story', 'channel'), name='unique_newsletter_story_channel'),
        ),
    ]
