# Generated by Django 5.2.17 on 2026-09-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_blog_distribution'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogpublication',
            new_name='core_blogpu_status_1648f3_idx',
            old_name='core_blogpub_status_lang_idx',
        ),
        migrations.AddField(
            model_name='newsletterschedule',
            name='company_daily_pattern',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='newsletterstory',
            name='company_activity_kind',
            field=models.CharField(blank=True, choices=[('activity', 'Company Activity'), ('visit', 'CEO Visit'), ('directive', 'CEO Directive')], max_length=30),
        ),
        migrations.AddField(
            model_name='newsletterstory',
            name='manager_action',
            field=models.TextField(blank=True),
        ),
    ]
