# Generated by Django 5.2.17 on 2026-09-25 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_core_blogpub_status_lang_idx_core_blogpu_status_1648f3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterstory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='newsletter/images/'),
        ),
        migrations.AddField(
            model_name='newsletterstory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='newsletter/videos/'),
        ),
        migrations.CreateModel(
            name='NewsletterSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='newsletter/submissions/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='newsletter/submissions/videos/')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('drafted', 'Draft Created'), ('rejected', 'Rejected')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newsletter_submissions', to=settings.AUTH_USER_MODEL)),
                ('generated_story', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submission', to='core.newsletterstory')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
