# Generated by Django 5.2.17 on 2026-09-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_newsletterstory_image_newsletterstory_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('kind', models.CharField(choices=[('iranian', 'Iranian'), ('shia', 'Shia'), ('company', 'Company Related')], max_length=20)),
                ('date_rule', models.CharField(help_text='ISO date or annually maintained date rule', max_length=80)),
                ('message_template', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('requires_owner_approval', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('kind', 'title'),
            },
        ),
        migrations.AddField(
            model_name='newslettersubmission',
            name='occasion_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='newslettersubmission',
            name='requested_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletterstory',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
