# Generated by Django 5.2.17 on 2026-09-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_seed_newsletter_occasions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('newsletter', 'Newsletter'), ('knowledge', 'Knowledge')], max_length=20)),
                ('target_path', models.CharField(help_text='Must point to a real /company/ page or anchor.', max_length=300)),
                ('relation', models.CharField(choices=[('primary', 'Primary'), ('related', 'Related')], default='related', max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='core.knowledgearticle')),
                ('newsletter_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='core.newsletterstory')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['target_path', 'content_type'], name='core_compan_target__107e8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyGalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='company/gallery/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='company/gallery/videos/')),
                ('target_path', models.CharField(blank=True, help_text='Optional Company Portal page/anchor.', max_length=300)),
                ('project_label', models.CharField(blank=True, max_length=200)),
                ('research_domain', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('newsletter_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_media', to='core.newsletterstory')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['media_type', 'published', 'published_at'], name='core_compan_media_t_b7780f_idx')],
            },
        ),
    ]
