# Generated by Django 5.2.17 on 2026-09-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_companycontentlink_companygallerymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubmission',
            name='company_target_paths',
            field=models.TextField(blank=True, help_text='One or more Company Portal paths, one per line, e.g. /company/product-1/'),
        ),
    ]
