# Generated by Django 5.2.17 on 2026-09-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_newslettersubmission_company_target_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('research', 'همکاری پژوهشی'), ('technology', 'فناوری و نوآوری'), ('project', 'پروژه و توسعه'), ('commercial', 'همکاری تجاری'), ('media', 'رسانه و محتوا')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'جدید'), ('reviewing', 'در حال بررسی'), ('approved', 'تأیید اولیه'), ('closed', 'بسته')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_compan_status_7e85d2_idx'), models.Index(fields=['kind', 'status'], name='core_compan_kind_46b268_idx')],
            },
        ),
    ]
