# Generated by Django 5.2.17 on 2026-09-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_newsletter_company_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubmission',
            name='body',
            field=models.TextField(help_text='فقط واقعیت\u200cها، فعالیت\u200cها، پژوهش\u200cها، پروژه\u200cها و خروجی\u200cهای ثبت\u200cشده شرکت.', verbose_name='شرح فعالیت شرکت'),
        ),
        migrations.AlterField(
            model_name='newslettersubmission',
            name='company_target_paths',
            field=models.TextField(blank=True, help_text='صفحات واقعی شرکت برای اتصال محتوا؛ فقط مسیرهای /company/.'),
        ),
        migrations.AlterField(
            model_name='newslettersubmission',
            name='occasion_code',
            field=models.CharField(blank=True, help_text='اختیاری؛ فقط برای دسته\u200cبندی داخلی فعالیت شرکت.', max_length=80),
        ),
        migrations.AlterField(
            model_name='newslettersubmission',
            name='subject',
            field=models.CharField(max_length=500, verbose_name='عنوان فعالیت شرکت'),
        ),
    ]
