# Generated by Django 5.2.17 on 2026-09-26 00:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_newslettersubmission_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeAgentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('mission', models.TextField()),
                ('goal', models.TextField()),
                ('start_date', models.DateField(default=datetime.date(2019, 11, 16))),
                ('cadence_hours', models.PositiveIntegerField(default=24)),
                ('active', models.BooleanField(default=True)),
                ('require_owner_approval', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=400)),
                ('domain', models.CharField(max_length=250)),
                ('objective', models.TextField()),
                ('source_policy', models.TextField(default='منابع معتبر، قابل ردیابی و تفکیک دیدگاه؛ بدون جعل منبع یا ادعای انتشار.')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('drafting', 'Drafting'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published')], default='planned', max_length=20)),
                ('volume_count', models.PositiveIntegerField(default=1)),
                ('generated_sections', models.PositiveIntegerField(default=0)),
                ('target_sections', models.PositiveIntegerField(default=24)),
                ('content', models.TextField(blank=True)),
                ('outline', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='core.knowledgeagentplan')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeAgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('objective', models.TextField()),
                ('output_summary', models.TextField(blank=True)),
                ('approval_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.knowledgeagentplan')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.knowledgebook')),
            ],
        ),
    ]
