# Generated by Django 5.2.17 on 2026-09-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_knowledgeagentplan_knowledgebook_knowledgeagentrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeagentplan',
            name='audience_goal',
            field=models.TextField(default='جذب مخاطب عمومی از جست\u200cوجو و تبدیل سایت به مرجع رایگان و قابل استناد.'),
        ),
        migrations.AddField(
            model_name='knowledgeagentplan',
            name='public_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='knowledgeagentplan',
            name='seo_first',
            field=models.BooleanField(default=True),
        ),
    ]
