# Generated by Django 5.2.17 on 2026-09-26 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_knowledgeagentplan_audience_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('scientific_scope', models.TextField()),
                ('priority', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.knowledgedomain')),
            ],
        ),
        migrations.AddField(
            model_name='knowledgebook',
            name='domain_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='core.knowledgedomain'),
        ),
    ]
