# Generated by Django 5.2.17 on 2026-09-26 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_knowledgedomain_knowledgebook_domain_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyActivityAgentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('mission', models.TextField()),
                ('cadence_hours', models.PositiveIntegerField(default=24)),
                ('reports_per_day', models.PositiveIntegerField(default=6)),
                ('active', models.BooleanField(default=True)),
                ('require_owner_approval', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY_DIGEST', 'Daily Digest'), ('ACTIVITY_ANALYSIS', 'Activity Analysis'), ('TREND_ANALYSIS', 'Trend Analysis'), ('UNIT_ANALYSIS', 'Unit Analysis'), ('PROJECT_ANALYSIS', 'Project Analysis'), ('EXECUTIVE_BRIEF', 'Executive Brief')], max_length=40)),
                ('title', models.CharField(max_length=400)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('source_activity_ids', models.JSONField(default=list)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published'), ('blocked', 'Blocked')], default='draft', max_length=20)),
                ('approval_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.companyactivityagentplan')),
            ],
            options={
                'indexes': [models.Index(fields=['report_type', 'period_end'], name='core_compan_report__f83cda_idx'), models.Index(fields=['status', 'created_at'], name='core_compan_status_d863b9_idx')],
            },
        ),
    ]
