# Generated by Django 5.2.17 on 2026-09-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_companyactivityagentplan_companyactivityreport'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companyactivityreport',
            constraint=models.UniqueConstraint(fields=('plan', 'report_type', 'period_start'), name='unique_company_activity_daily_report'),
        ),
    ]
