# Generated by Django 5.2.17 on 2026-09-26 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_companyactivityreport_unique_company_activity_daily_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeEmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('trade_context', models.JSONField(default=dict)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=200)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=False)),
                ('allow_outbound', models.BooleanField(default=False)),
                ('require_policy_gate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trade Mailbox',
                'verbose_name_plural': 'Trade Mailboxes',
            },
        ),
        migrations.CreateModel(
            name='TradeEmailAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('actor_type', models.CharField(default='economic-agent', max_length=30)),
                ('trace_id', models.CharField(db_index=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='core.tradeemailoutbox')),
            ],
        ),
        migrations.AddField(
            model_name='tradeemailoutbox',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox', to='core.trademailbox'),
        ),
        migrations.AddIndex(
            model_name='tradeemailoutbox',
            index=models.Index(fields=['mailbox', 'status'], name='core_tradee_mailbox_28d142_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeemailoutbox',
            index=models.Index(fields=['created_at'], name='core_tradee_created_5e8e2f_idx'),
        ),
    ]
