# Generated by Django 5.2.17 on 2026-09-26 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_educationcourse_educationtrack_educationlesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcourse',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='education_course', to='core.product'),
        ),
    ]
