# Generated by Django 5.2.17 on 2026-09-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_educationcourse_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcourse',
            name='quality_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationcourse',
            name='quality_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='educationcourse',
            name='quality_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
