# Generated by Django 5.2.17 on 2026-09-26 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_educationcourse_quality_checked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('audience', models.CharField(choices=[('teacher', 'Teacher'), ('professor', 'Professor'), ('coach', 'Coach')], default='teacher', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('slide_count', models.PositiveIntegerField(default=0)),
                ('file_url', models.URLField(blank=True)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('presenter_notes', models.TextField(blank=True)),
                ('lesson_plan', models.JSONField(default=list)),
                ('classroom_activities', models.JSONField(default=list)),
                ('assessment_notes', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_free', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('quality_status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='core.educationcourse')),
            ],
            options={
                'ordering': ['course__id', 'id'],
            },
        ),
    ]
