from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Product
from .brand import brand_for_request
from .services_views import services


FACTORY_CATALOG = {
 "products": {"title":"Products","kicker":"FACTORY / PRODUCTS","headline":"Products built to solve real problems.","body":"A catalog for verified digital products, tools and future physical offerings produced by the Factory.","cards":[("Digital Products","Software · Files · Tools","Downloadable and software products with explicit delivery terms."),("Business Tools","Operations","Practical tools for costing, workflow, research and productivity."),("New Products","Evidence-led","New categories appear only when the Factory has a real product to offer.")]},
 "services": {"title":"Services","kicker":"FACTORY / SERVICES","headline":"A broad service layer for digital business.","body":"Productized services designed for clear scope, delivery and support.","cards":[("AI & Automation","Build · Integrate","Automation workflows, AI-assisted systems and operational tooling."),("Software & Web","Design · Engineering","Web applications, business systems and digital experiences."),("Research & Content","Evidence · Localization","Research-backed content, localization and digital production services.")]},
 "ai": {"title":"AI & Automation","kicker":"FACTORY / AI","headline":"AI systems with an operational purpose.","body":"Automation, assistants, research workflows and business tooling packaged as products or services.","cards":[("Automation","Workflow","Repeatable business workflows with measurable outputs."),("AI Assistants","Product","Purpose-built assistants connected to approved data and tools."),("Research Systems","Evidence","Structured discovery, evidence and analysis pipelines.")]},
 "software": {"title":"Software","kicker":"FACTORY / SOFTWARE","headline":"Software produced, tested and packaged by the Factory.","body":"Web apps, utilities, SaaS candidates and downloadable software can each receive their own commercial product page.","cards":[("Web Applications","Product","Responsive applications with defined use cases."),("SaaS","Recurring","Subscription-ready services when operations and billing are verified."),("Utilities","Downloadable","Focused tools with direct digital delivery.")]},
 "commerce": {"title":"Commerce","kicker":"REVENUE / COMMERCE","headline":"One commercial layer for many kinds of value.","body":"Products and services flow through catalog, offer, checkout, order, delivery and support without pretending an unavailable payment rail exists.","cards":[("Store","Catalog","Sell eligible digital and future physical products."),("Service Orders","Scope","Turn productized services into trackable orders."),("Subscriptions","Recurring","Recurring plans only when billing and cancellation flows are operational.")]},
 "crypto-payments": {"title":"Crypto Payments","kicker":"COMMERCE / CRYPTO","headline":"On-chain payments with verification before fulfillment.","body":"Crypto checkout and wallet connectivity for eligible products, with treasury actions kept outside autonomous authority.","cards":[("Crypto Checkout","Order-bound","Network, asset, amount and confirmations are bound to the order."),("Wallet Connection","Signed ownership","Customer addresses are verified without custody of private keys."),("Treasury Safety","Owner controlled","Incoming reconciliation is separate from withdrawals, swaps and trades.")]},
 "blockchain": {"title":"Blockchain & Web3","kicker":"FACTORY / WEB3","headline":"Blockchain products with utility before speculation.","body":"Build and sell eligible blockchain software and services with security, network and market checks before activation.","cards":[("Smart Contract Services","Engineering","Design, implementation and verification for legitimate use cases."),("Web3 Applications","Software","Wallet-aware applications and blockchain integrations."),("Tokenized Utility","Governed","Utility/tokenized products only after legal, security and market eligibility gates.")]},
 "studio": {"title":"Creative Studio","kicker":"FACTORY / STUDIO","headline":"Digital media produced as commercial assets.","body":"Brand, design, interactive media and content packages can become standalone offers with explicit licensing and delivery.","cards":[("Brand & Design","Creative","Digital identity and visual production."),("Interactive Media","Experience","Interactive assets and product experiences."),("Content Production","Multilingual","Localized content packages built for specific markets.")]},
 "research-lab": {"title":"Research Lab","kicker":"FACTORY / RESEARCH","headline":"Research can itself become a product.","body":"Evidence-backed reports, market intelligence and decision-support packages with traceable sources.","cards":[("Market Research","Evidence","Structured market and opportunity research."),("Industry Briefs","Reports","Focused commercial intelligence packages."),("Localization Research","Markets","Language and market adaptation research.")]},
 "game-factory": {"title":"Game Factory","kicker":"FACTORY / GAMES","headline":"Original games from prototype to evolving world.","body":"Game production has its own commercial surface while sharing the Factory's evidence, QA and packaging backbone.","cards":[("Original Games","IP","Independent game worlds and mechanics."),("Playable Experiments","R&D","Small releases used to validate gameplay."),("Live Products","Future","Live operations only after a real released product exists.")]},
}

CORPORATE_FUTURE = {
 "global-business": {"title":"Global Business","kicker":"ZOMOROD / GLOBAL","headline":"Built for global products, services and future expansion.","body":"A future-ready commercial structure spanning technology, digital products, services, games, research, commerce and agro-industry. Current operations and future legal entities are kept explicitly distinct.","cards":[("Global Products & Services","Worldwide","A shared commercial foundation designed for localization, market eligibility, pricing and delivery by market."),("USA-first Games","MojPlayWin","Games are designed with the United States as the initial target market, with later international expansion."),("Canada Vision","Future","Infrastructure is being prepared for a future Canadian multipurpose and agro-industrial company; incorporation is not claimed before it occurs.")]},
 "agro-industry": {"title":"Agro-Industry","kicker":"FUTURE / AGRO-INDUSTRY","headline":"A long-term production pillar beyond digital business.","body":"A future business unit for agriculture, food, processing, trade and related industrial activity. Public claims will expand only as real operations and evidence exist.","cards":[("Agriculture","Future production","Production concepts and research can be prepared now without claiming active Canadian operations."),("Food & Processing","Future industry","A foundation for future products, processing and commercial supply chains."),("Trade & Export","Market-led","International trade capabilities can connect later to verified products, entities and logistics.")]},
 "canada-vision": {"title":"Canada Vision","kicker":"FUTURE / CANADA","headline":"Preparing today for a future Canadian operating structure.","body":"The platform is being designed so a future Canadian legal entity can connect to brands, business units, contracts, payments and operations without rebuilding the system from zero.","cards":[("Multipurpose Company","Future structure","Technology, commerce, services and production can operate as distinct business units under an appropriate future legal structure."),("Agro-Industrial Pillar","Long term","Agriculture and industry remain a core long-term business direction."),("Legal Separation","Governance","A future Canadian entity will only be represented as incorporated after real registration and verification.")]},
}

PAGES = {
 "games": {"title":"Games","kicker":"PLAY / DISCOVER","headline":"Games built around meaningful choices.","body":"Explore original MojPlayWin projects, playable experiments and worlds in development.","cards":[("First Realm","Strategy · World Building","In development. An original strategy world focused on expansion, decisions and a living economy."),("Next World","Original IP","Reserved for the next independently designed MojPlayWin title."),("Experiments","Playable R&D","Small prototypes used to validate mechanics before they become full games.")]},
 "worlds":{"title":"Worlds","kicker":"LORE / SYSTEMS","headline":"Worlds designed to evolve.","body":"Every MojPlayWin universe starts with its own rules, identity and reason to exist.","cards":[("Systems First","Design","World rules react to player decisions."),("Living Economies","Simulation","Progression and resources are designed as coherent systems."),("Original Identity","IP","Distinct mechanics and visual direction for every world.")]},
 "news":{"title":"News","kicker":"STUDIO / SIGNAL","headline":"Development, without invented milestones.","body":"Verified development notes and release updates will appear here as projects advance.","cards":[("Development","Updates","Production milestones and build notes."),("Design Notes","Inside the systems","How mechanics move from hypothesis to tested gameplay."),("Release Notes","When available","Changes tied to real released builds.")]},
 "community":{"title":"Community","kicker":"PLAYERS / FEEDBACK","headline":"Players help decide what grows.","body":"Testing and feedback channels will open when playable builds are ready.","cards":[("Playtests","Coming when ready","Structured testing for eligible builds."),("Feedback","Player signal","Actionable feedback feeds product decisions."),("Community Safety","Baseline","Respectful participation and clear moderation rules.")]},
 "support":{"title":"Support","kicker":"HELP / ACCESS","headline":"Support that starts with the actual problem.","body":"Game and account support will expand alongside released products.","cards":[("General Help","support@mojplaywin.com","Contact the support mailbox for general questions."),("Game Issues","Release-linked","Game-specific help opens with each public build."),("Account Help","Planned","Account recovery and profile support will be connected when accounts launch.")]},
 "about":{"title":"About","kicker":"MOJPLAYWIN / STUDIO","headline":"Original games. Measured evolution.","body":"MojPlayWin is being built as a global gaming brand for original digital games and interactive worlds.","cards":[("Original by Default","Principle","No reskins or invented release claims."),("Player First","Principle","Gameplay and player signal guide iteration."),("Global by Design","Principle","Architecture is prepared for multiple markets and languages.")]},
 "contact":{"title":"Contact","kicker":"CONTACT / MOJPLAYWIN","headline":"Talk to MojPlayWin.","body":"Use the appropriate channel so your message reaches the right workflow.","cards":[("Support","support@mojplaywin.com","Player and game support."),("Business","Coming soon","Business contact will be published only after the mailbox is operational."),("Press","Coming soon","Press resources will be added with verified public releases.")]},
 "privacy":{"title":"Privacy","kicker":"LEGAL / PRIVACY","headline":"Privacy information.","body":"This page is a publication-ready placeholder, not a substitute for jurisdiction-specific legal review.","cards":[("Data minimization","Policy direction","Collect only data required to operate the service."),("Security","Policy direction","Protect access and retain auditable operational controls."),("Rights","Before launch","Final rights, retention and contact terms must match actual deployed services.")]},
 "terms":{"title":"Terms","kicker":"LEGAL / TERMS","headline":"Terms of service.","body":"Final binding terms will be published before accounts, payments or public game services are activated.","cards":[("Fair use","Baseline","Services must not be abused or used unlawfully."),("Digital services","Before launch","Product-specific rules will match the actual released service."),("Changes","Transparent","Material terms should be versioned and communicated.")]},
 "cookies":{"title":"Cookies","kicker":"LEGAL / COOKIES","headline":"Cookie information.","body":"Cookie disclosures will reflect the trackers actually deployed; unnecessary tracking is not assumed.","cards":[("Essential","Operational","Required security/session technologies may be used."),("Analytics","Consent-aware","Analytics should only be enabled under the applicable consent policy."),("Advertising","Not assumed","No advertising tracker is claimed until one is actually configured.")]},
}
def branded_home(request):
    brand=brand_for_request(request)
    if brand:return render(request,brand.template,{"brand":brand})
    return services(request)
def branded_product(request, pk):
    brand=brand_for_request(request)
    if not brand or brand.code!="mojplaywin": raise Http404
    product=get_object_or_404(Product, pk=pk, active=True)
    return render(request,"brands/mojplaywin/product.html",{"brand":brand,"product":product})

def branded_product(request, pk):
    brand=brand_for_request(request)
    if not brand or brand.code!="mojplaywin": raise Http404
    product=get_object_or_404(Product, pk=pk, active=True)
    return render(request,"brands/mojplaywin/product.html",{"brand":brand,"product":product})

def branded_store(request):
    brand=brand_for_request(request)
    if not brand or brand.code!="mojplaywin": raise Http404
    products=Product.objects.filter(active=True).order_by("-id")
    return render(request,"brands/mojplaywin/store.html",{"brand":brand,"products":products})

def branded_page(request, page):
    brand=brand_for_request(request)
    if not brand or brand.code!="mojplaywin": raise Http404
    data=PAGES.get(page) or FACTORY_CATALOG.get(page) or CORPORATE_FUTURE.get(page)
    if not data: raise Http404
    return render(request,"brands/mojplaywin/page.html",{"brand":brand,"page":data,"page_key":page})
def branded_game(request, slug):
    brand=brand_for_request(request)
    if not brand or brand.code!="mojplaywin" or slug!="first-realm": raise Http404
    return render(request,"brands/mojplaywin/game.html",{"brand":brand})
