"""Editorial specifications for 40 independent MojPlayWin specialty routes."""
SPECIALTIES = {
    "products/software-products": {
        "kind": "products", "title": "Software Products",
        "focus": "Architecture, packaging, and versioned distribution",
        "checks": "Compatibility, licensing, and maintenance scope",
        "intro": "Software Products are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify architecture, packaging, and versioned distribution; prototype; independently test; publish only after release authorization.",
        "accent": "#56b9ff",
        "status": "editorial_draft",
    },
    "products/web-applications": {
        "kind": "products", "title": "Web Applications",
        "focus": "Browser delivery, accessibility, and server-side security",
        "checks": "Supported browsers, hosting dependencies, and privacy",
        "intro": "Web Applications are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify browser delivery, accessibility, and server-side security; prototype; independently test; publish only after release authorization.",
        "accent": "#a99cff",
        "status": "editorial_draft",
    },
    "products/mobile-apps": {
        "kind": "products", "title": "Mobile Apps",
        "focus": "Native and cross-platform app engineering",
        "checks": "Platform compatibility, permissions, and release channels",
        "intro": "Mobile Apps are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify native and cross-platform app engineering; prototype; independently test; publish only after release authorization.",
        "accent": "#f4b860",
        "status": "editorial_draft",
    },
    "products/mobile-games": {
        "kind": "products", "title": "Mobile Games",
        "focus": "Touch controls, device performance, and player progression",
        "checks": "Age suitability, supported devices, and update cadence",
        "intro": "Mobile Games are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify touch controls, device performance, and player progression; prototype; independently test; publish only after release authorization.",
        "accent": "#7bd6bd",
        "status": "editorial_draft",
    },
    "products/browser-games": {
        "kind": "products", "title": "Browser Games",
        "focus": "Web runtime, loading budgets, and input accessibility",
        "checks": "Browser support, offline behavior, and session persistence",
        "intro": "Browser Games are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify web runtime, loading budgets, and input accessibility; prototype; independently test; publish only after release authorization.",
        "accent": "#e6a6d9",
        "status": "editorial_draft",
    },
    "products/strategy-games": {
        "kind": "products", "title": "Strategy Games",
        "focus": "Decision systems, balancing, and scenario design",
        "checks": "Rules transparency, difficulty, and save systems",
        "intro": "Strategy Games are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify decision systems, balancing, and scenario design; prototype; independently test; publish only after release authorization.",
        "accent": "#a5c86b",
        "status": "editorial_draft",
    },
    "products/educational-games": {
        "kind": "products", "title": "Educational Games",
        "focus": "Learning objectives, assessment design, and inclusive play",
        "checks": "Curriculum alignment, accessibility, and safeguarding",
        "intro": "Educational Games are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify learning objectives, assessment design, and inclusive play; prototype; independently test; publish only after release authorization.",
        "accent": "#edaa87",
        "status": "editorial_draft",
    },
    "products/multiplayer-games": {
        "kind": "products", "title": "Multiplayer Games",
        "focus": "Matchmaking, synchronization, and fair-play design",
        "checks": "Server availability, moderation, and data retention",
        "intro": "Multiplayer Games are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify matchmaking, synchronization, and fair-play design; prototype; independently test; publish only after release authorization.",
        "accent": "#8fb9e9",
        "status": "editorial_draft",
    },
    "products/ai-tools": {
        "kind": "products", "title": "AI Tools",
        "focus": "Model evaluation, task boundaries, and explainable outputs",
        "checks": "Data handling, accuracy limits, and human oversight",
        "intro": "AI Tools are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify model evaluation, task boundaries, and explainable outputs; prototype; independently test; publish only after release authorization.",
        "accent": "#56b9ff",
        "status": "editorial_draft",
    },
    "products/ai-assistants": {
        "kind": "products", "title": "AI Assistants",
        "focus": "Conversation design, retrieval quality, and escalation",
        "checks": "Privacy, supported tasks, and failure handling",
        "intro": "AI Assistants are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify conversation design, retrieval quality, and escalation; prototype; independently test; publish only after release authorization.",
        "accent": "#a99cff",
        "status": "editorial_draft",
    },
    "products/ai-agents": {
        "kind": "products", "title": "AI Agents",
        "focus": "Tool permissions, execution traces, and approval gates",
        "checks": "Autonomy boundaries, audit logs, and owner authorization",
        "intro": "AI Agents are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify tool permissions, execution traces, and approval gates; prototype; independently test; publish only after release authorization.",
        "accent": "#f4b860",
        "status": "editorial_draft",
    },
    "products/automation-systems": {
        "kind": "products", "title": "Automation Systems",
        "focus": "Workflow orchestration, retries, and monitoring",
        "checks": "Integration scope, rollback, and service dependencies",
        "intro": "Automation Systems are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify workflow orchestration, retries, and monitoring; prototype; independently test; publish only after release authorization.",
        "accent": "#7bd6bd",
        "status": "editorial_draft",
    },
    "products/software-bots": {
        "kind": "products", "title": "Software Bots",
        "focus": "Event-driven tasks, rate limits, and safe credentials",
        "checks": "Platform terms, access permissions, and monitoring",
        "intro": "Software Bots are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify event-driven tasks, rate limits, and safe credentials; prototype; independently test; publish only after release authorization.",
        "accent": "#e6a6d9",
        "status": "editorial_draft",
    },
    "products/saas-products": {
        "kind": "products", "title": "SaaS Products",
        "focus": "Tenant isolation, subscriptions, and service reliability",
        "checks": "Service levels, billing terms, and account deletion",
        "intro": "SaaS Products are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify tenant isolation, subscriptions, and service reliability; prototype; independently test; publish only after release authorization.",
        "accent": "#a5c86b",
        "status": "editorial_draft",
    },
    "products/plugins-extensions": {
        "kind": "products", "title": "Plugins & Extensions",
        "focus": "Host compatibility, permissions, and versioning",
        "checks": "Supported platforms, installation, and security updates",
        "intro": "Plugins & Extensions are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify host compatibility, permissions, and versioning; prototype; independently test; publish only after release authorization.",
        "accent": "#edaa87",
        "status": "editorial_draft",
    },
    "products/website-templates": {
        "kind": "products", "title": "Website Templates",
        "focus": "Responsive components, semantic markup, and customization",
        "checks": "Accessibility, licensing, and browser testing",
        "intro": "Website Templates are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify responsive components, semantic markup, and customization; prototype; independently test; publish only after release authorization.",
        "accent": "#8fb9e9",
        "status": "editorial_draft",
    },
    "products/e-commerce-templates": {
        "kind": "products", "title": "E-commerce Templates",
        "focus": "Product discovery, checkout integration, and trust signals",
        "checks": "Payment provider compatibility, tax configuration, and fulfillment",
        "intro": "E-commerce Templates are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify product discovery, checkout integration, and trust signals; prototype; independently test; publish only after release authorization.",
        "accent": "#56b9ff",
        "status": "editorial_draft",
    },
    "products/apis-sdks": {
        "kind": "products", "title": "APIs & SDKs",
        "focus": "Endpoint contracts, authentication, and developer experience",
        "checks": "Rate limits, changelogs, and credential safety",
        "intro": "APIs & SDKs are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify endpoint contracts, authentication, and developer experience; prototype; independently test; publish only after release authorization.",
        "accent": "#a99cff",
        "status": "editorial_draft",
    },
    "products/data-analytics-tools": {
        "kind": "products", "title": "Data Analytics Tools",
        "focus": "Data pipelines, metrics definitions, and dashboards",
        "checks": "Source provenance, consent, and reporting accuracy",
        "intro": "Data Analytics Tools are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify data pipelines, metrics definitions, and dashboards; prototype; independently test; publish only after release authorization.",
        "accent": "#f4b860",
        "status": "editorial_draft",
    },
    "products/business-dashboards": {
        "kind": "products", "title": "Business Dashboards",
        "focus": "Operational KPIs, role-based access, and reporting",
        "checks": "Data refresh rates, permissions, and decision limits",
        "intro": "Business Dashboards are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify operational kpis, role-based access, and reporting; prototype; independently test; publish only after release authorization.",
        "accent": "#7bd6bd",
        "status": "editorial_draft",
    },
    "products/security-software": {
        "kind": "products", "title": "Security Software",
        "focus": "Threat modeling, defensive checks, and patch lifecycle",
        "checks": "Security scope, false positives, and independent validation",
        "intro": "Security Software are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify threat modeling, defensive checks, and patch lifecycle; prototype; independently test; publish only after release authorization.",
        "accent": "#e6a6d9",
        "status": "editorial_draft",
    },
    "products/digital-design-assets": {
        "kind": "products", "title": "Digital Design Assets",
        "focus": "Reusable visual systems, formats, and licensing",
        "checks": "Usage rights, resolution, and editable formats",
        "intro": "Digital Design Assets are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify reusable visual systems, formats, and licensing; prototype; independently test; publish only after release authorization.",
        "accent": "#a5c86b",
        "status": "editorial_draft",
    },
    "products/3d-assets": {
        "kind": "products", "title": "3D Assets",
        "focus": "Geometry optimization, materials, and export formats",
        "checks": "Polygon budgets, engine compatibility, and licenses",
        "intro": "3D Assets are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify geometry optimization, materials, and export formats; prototype; independently test; publish only after release authorization.",
        "accent": "#edaa87",
        "status": "editorial_draft",
    },
    "products/web3-products": {
        "kind": "products", "title": "Web3 Products",
        "focus": "Wallet connectivity, on-chain verification, and network risks",
        "checks": "Chain compatibility, custody, and transaction fees",
        "intro": "Web3 Products are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify wallet connectivity, on-chain verification, and network risks; prototype; independently test; publish only after release authorization.",
        "accent": "#8fb9e9",
        "status": "editorial_draft",
    },
    "products/digital-learning-products": {
        "kind": "products", "title": "Digital Learning Products",
        "focus": "Modular lessons, progress design, and accessible formats",
        "checks": "Prerequisites, learning outcomes, and content revisions",
        "intro": "Digital Learning Products are a specialist product category in MojPlayWin's digital production roadmap. This page documents technical considerations and release evidence; it does not represent an item currently for sale.",
        "workflow": "Research the intended users; specify modular lessons, progress design, and accessible formats; prototype; independently test; publish only after release authorization.",
        "accent": "#56b9ff",
        "status": "editorial_draft",
    },
    "services/website-development": {
        "kind": "services", "title": "Website Development",
        "focus": "Discovery, information architecture, and responsive implementation",
        "checks": "Deliverables, hosting responsibilities, and accessibility review",
        "intro": "Website Development is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around discovery, information architecture, and responsive implementation; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#a99cff",
        "status": "editorial_draft",
    },
    "services/custom-software-development": {
        "kind": "services", "title": "Custom Software Development",
        "focus": "Requirements mapping, system design, and maintainable code",
        "checks": "Scope control, security review, and acceptance criteria",
        "intro": "Custom Software Development is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around requirements mapping, system design, and maintainable code; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#f4b860",
        "status": "editorial_draft",
    },
    "services/app-development-services": {
        "kind": "services", "title": "App Development Services",
        "focus": "Platform selection, interface prototyping, and release preparation",
        "checks": "Device coverage, app-store rules, and maintenance",
        "intro": "App Development Services is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around platform selection, interface prototyping, and release preparation; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#7bd6bd",
        "status": "editorial_draft",
    },
    "services/game-development-services": {
        "kind": "services", "title": "Game Development Services",
        "focus": "Gameplay prototypes, engine workflows, and quality assurance",
        "checks": "Platform targets, art pipeline, and playtesting",
        "intro": "Game Development Services is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around gameplay prototypes, engine workflows, and quality assurance; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#e6a6d9",
        "status": "editorial_draft",
    },
    "services/ai-development-services": {
        "kind": "services", "title": "AI Development Services",
        "focus": "Use-case validation, data readiness, and model evaluation",
        "checks": "Privacy, human oversight, and measurable acceptance",
        "intro": "AI Development Services is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around use-case validation, data readiness, and model evaluation; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#a5c86b",
        "status": "editorial_draft",
    },
    "services/workflow-automation": {
        "kind": "services", "title": "Workflow Automation",
        "focus": "Process mapping, integration design, and failure recovery",
        "checks": "Access scopes, retries, and operational ownership",
        "intro": "Workflow Automation is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around process mapping, integration design, and failure recovery; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#edaa87",
        "status": "editorial_draft",
    },
    "services/ai-agent-development": {
        "kind": "services", "title": "AI Agent Development",
        "focus": "Agent boundaries, tool permissions, and evaluation harnesses",
        "checks": "Approval gates, auditability, and safe handoff",
        "intro": "AI Agent Development is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around agent boundaries, tool permissions, and evaluation harnesses; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#8fb9e9",
        "status": "editorial_draft",
    },
    "services/design-branding": {
        "kind": "services", "title": "Design & Branding",
        "focus": "Visual identity systems, design research, and accessible components",
        "checks": "Brand rights, deliverable formats, and usage guidelines",
        "intro": "Design & Branding is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around visual identity systems, design research, and accessible components; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#56b9ff",
        "status": "editorial_draft",
    },
    "services/content-production": {
        "kind": "services", "title": "Content Production",
        "focus": "Editorial research, structured writing, and review workflows",
        "checks": "Source accuracy, originality, and publication approval",
        "intro": "Content Production is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around editorial research, structured writing, and review workflows; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#a99cff",
        "status": "editorial_draft",
    },
    "services/video-animation": {
        "kind": "services", "title": "Video & Animation",
        "focus": "Storyboards, motion design, and delivery formats",
        "checks": "Usage rights, captioning, and production milestones",
        "intro": "Video & Animation is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around storyboards, motion design, and delivery formats; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#f4b860",
        "status": "editorial_draft",
    },
    "services/seo-services": {
        "kind": "services", "title": "SEO Services",
        "focus": "Technical crawling, information architecture, and content quality",
        "checks": "Search guidelines, measurable outcomes, and no ranking guarantees",
        "intro": "SEO Services is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around technical crawling, information architecture, and content quality; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#7bd6bd",
        "status": "editorial_draft",
    },
    "services/digital-marketing": {
        "kind": "services", "title": "Digital Marketing",
        "focus": "Audience segmentation, channel planning, and attribution",
        "checks": "Consent, advertising rules, and budget accountability",
        "intro": "Digital Marketing is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around audience segmentation, channel planning, and attribution; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#e6a6d9",
        "status": "editorial_draft",
    },
    "services/social-media-management": {
        "kind": "services", "title": "Social Media Management",
        "focus": "Channel strategy, editorial calendars, and moderation workflows",
        "checks": "Account authorization, platform policies, and reporting",
        "intro": "Social Media Management is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around channel strategy, editorial calendars, and moderation workflows; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#a5c86b",
        "status": "editorial_draft",
    },
    "services/market-research": {
        "kind": "services", "title": "Market Research",
        "focus": "Research questions, source triangulation, and demand analysis",
        "checks": "Sample bias, evidence quality, and uncertainty",
        "intro": "Market Research is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around research questions, source triangulation, and demand analysis; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#edaa87",
        "status": "editorial_draft",
    },
    "services/translation-localization": {
        "kind": "services", "title": "Translation & Localization",
        "focus": "Terminology management, cultural adaptation, and language QA",
        "checks": "Locale conventions, reviewer signoff, and accessibility",
        "intro": "Translation & Localization is a specialist service discipline within MojPlayWin's proposed virtual services. This page explains the delivery approach and qualification requirements; it does not imply bookings are open.",
        "workflow": "Qualify the request; define scope around terminology management, cultural adaptation, and language qa; document milestones; review quality; accept orders only after operational approval.",
        "accent": "#8fb9e9",
        "status": "editorial_draft",
    },
}
